id=gcp
name=GCP Secret Manager Secret Provider
version=${project.version}
description=Resolves Gravitee secrets from GCP Secret Manager
class=io.fluenthealth.gravitee.secretprovider.gcp.GcpSecretProviderFactory
type=secret-provider
